#!/bin/bash

# -d Jun1123, date
# -o, open
# -u, upload

usage() {
  echo "Usage: $0 [-d DATE] [-o] [-u]" 1>&2
  exit 1
}

while getopts "d:ouh" OPTION; do
  case "${OPTION}" in
    d)
      DATE=$OPTARG
      ;;
    o)
      OPEN=true
      ;;
    u)
      UPLOAD=true
      ;;
    h)
      usage
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

# if no date, use today
if [ -z "$DATE" ]
then
  DATE=$(date +"%b%d%y")
fi

# read cookie from cookie.txt, where this file is located
DIR=$(dirname $0)
COOKIE=$(cat $DIR/cookie.txt)

# if no cookie, print error
if [ -z "$COOKIE" ]
then
  echo "Error: cookie.txt is empty"
  exit 1
fi

curl "https://www.nytimes.com/svc/crosswords/v2/puzzle/print/$DATE.pdf" \
  --silent \
  -o $DATE.pdf \
  -H 'authority: www.nytimes.com' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cache-control: max-age=0' \
  -H "cookie: ${COOKIE}" \
  -H 'dnt: 1' \
  -H 'referer: https://www.nytimes.com/crosswords' \
  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  --compressed

if [ "$OPEN" == true ]
then
  open $DATE.pdf
fi

if [ "$UPLOAD" == true ]
then
  # convert %b%d%y to Saturday, June 11, 2023
  FULLDATE=$(date -j -f "%b%d%y" $DATE +"%A, %B %d, %Y")

  rmapi put $DATE.pdf
  rmapi mv $DATE "$FULLDATE"
fi
